###
GET http://localhost:3000/api/v1/users

###
DELETE http://localhost:3000/api/v1/posts/1

###
GET http://localhost:3000/api/v1/users/search?query=John

###
GET http://localhost:3000/api/v1/posts/id

