###
GET http://localhost:3000/api/v1/users/

###
DELETE http://localhost:3000/api/v1/posts/9

###
POST http://localhost:3000/api/v1/posts/search?q=s

###
POST http://localhost:3000/api/v1/users/search?q=j

###
GET http://localhost:3000/api/v1/posts


###
POST http://localhost:3000/api/v1/posts/seed

###
POST http://localhost:3000/api/v1/users/seed

###
GET http://localhost:3000/api/v1/

### 
PATCH http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
    "fullName": "Tommy Bahama"
}

//patch a post
###
PATCH http://localhost:3000/api/v1/posts/1
Content-Type: application/json

{
    "caption": "Check out this new test"
}

//create user
###
POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{
    "fullName": "Moshe Plotkin",
    "email": "plotkinm@newpaltz.edu",
    "password": "1231234",
    "role": "user"
}

//login user
###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "plotkinm@newpaltz.edu",
    "password": "1231234"
}

//generate a new ImageURL
###
PATCH http://localhost:3000/api/v1/posts/generate/3




